@urlApi = https://localhost:7098/api
@urlAuth = https://auth.monno.tech/realms/development


### Generate Token - Machine to Machine
POST {{urlAuth}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=monno-service-customers&client_secret=yRr4dlkOgGTkJdke1GJEVPpJxPLVqZNc&grant_type=client_credentials


### Create a new customer
POST {{urlApi}}/customers
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@gmail.com",
    "phoneNumber": "(910) 371-3690",
    "userContext":{
        "ipAddress": "193.186.4.240"
    }
}
